// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AccessType.
const (
	HOMEWORLD   AccessType = "HOME_WORLD"
	LINKEDWORLD AccessType = "LINKED_WORLD"
)

// Defines values for Status.
const (
	ACCESSDENIEDACCOUNTNOTLINKED      Status = "ACCESS_DENIED_ACCOUNT_NOT_LINKED"
	ACCESSDENIEDBANNED                Status = "ACCESS_DENIED_BANNED"
	ACCESSDENIEDEXPIRED               Status = "ACCESS_DENIED_EXPIRED"
	ACCESSDENIEDINVALIDWORLD          Status = "ACCESS_DENIED_INVALID_WORLD"
	ACCESSDENIEDREQUIREMENTNOTMET     Status = "ACCESS_DENIED_REQUIREMENT_NOT_MET"
	ACCESSDENIEDUNKNOWN               Status = "ACCESS_DENIED_UNKNOWN"
	ACCESSGRANTEDHOMEWORLD            Status = "ACCESS_GRANTED_HOME_WORLD"
	ACCESSGRANTEDHOMEWORLDTEMPORARY   Status = "ACCESS_GRANTED_HOME_WORLD_TEMPORARY"
	ACCESSGRANTEDLINKEDWORLD          Status = "ACCESS_GRANTED_LINKED_WORLD"
	ACCESSGRANTEDLINKEDWORLDTEMPORARY Status = "ACCESS_GRANTED_LINKED_WORLD_TEMPORARY"
)

// APIKeyData defines model for APIKeyData.
type APIKeyData struct {
	// Apikey The api to set for the user
	Apikey string `json:"apikey"`

	// Primary Set if the user should be the primary user of that particular platform. There can only be one per platform per account. Setting a new primary user will override the old one
	Primary bool `json:"primary"`
}

// APIKeyName defines model for APIKeyName.
type APIKeyName struct {
	// Name The apikey name the user has to name their apikey if apikey name is enforced
	Name string `json:"name"`
}

// AccessType defines model for AccessType.
type AccessType string

// Account defines model for Account.
type Account struct {
	Access       *[]string   `json:"access,omitempty"`
	Age          int         `json:"age"`
	ApiKeys      []TokenInfo `bun:"rel:has-many,join:id=account_id" json:"api_keys"`
	Commander    bool        `json:"commander"`
	Created      time.Time   `json:"created"`
	DailyAp      *int        `json:"daily_ap,omitempty"`
	DbCreated    time.Time   `bun:",nullzero,notnull,default:current_timestamp,scanonly" json:"db_created,omitempty"`
	DbUpdated    time.Time   `bun:",nullzero,notnull,default:current_timestamp" json:"db_updated,omitempty"`
	Expired      *bool       `bun:"-" json:"expired,omitempty"`
	FractalLevel *int        `json:"fractal_level,omitempty"`
	GuildLeader  *[]string   `json:"guild_leader,omitempty"`
	Guilds       *[]string   `json:"guilds,omitempty"`
	ID           string      `bun:",pk" json:"id"`
	LastModified *time.Time  `json:"last_modified,omitempty"`
	MonthlyAp    *int        `json:"monthly_ap,omitempty"`
	Name         string      `json:"name"`
	UserID       int64       `json:"user_id"`
	World        int         `json:"world"`
	WorldStatus  *Status     `bun:"-" json:"world_status,omitempty"`
	WvWGuildID   *string     `bun:"wvw_guild_id" json:"wvw_guild_id,omitempty"`
	WvWRank      int         `bun:"wvw_rank" json:"wvw_rank"`
	WvWTeamID    int         `bun:"wvw_team_id" json:"wvw_team_id"`
}

// Ban defines model for Ban.
type Ban struct {
	Reason string    `json:"reason"`
	Until  time.Time `json:"until"`
	UserID int64     `json:"user_id"`
}

// ChannelMetadata defines model for ChannelMetadata.
type ChannelMetadata struct {
	Name  string                `json:"name"`
	Users []ChannelUserMetadata `json:"users"`
}

// ChannelUserMetadata defines model for ChannelUserMetadata.
type ChannelUserMetadata struct {
	Deafened  bool   `json:"deafened"`
	Id        string `json:"id"`
	Muted     bool   `json:"muted"`
	Name      string `json:"name"`
	Streaming bool   `json:"streaming"`
}

// Configuration defines model for Configuration.
type Configuration struct {
	ExpirationTime                int `json:"expiration_time"`
	TemporaryAccessExpirationTime int `json:"temporary_access_expiration_time"`

	// WorldLinks List of worlds links
	WorldLinks map[string]WorldLinks `json:"world_links"`
}

// EphemeralAssociation defines model for EphemeralAssociation.
type EphemeralAssociation struct {
	AccessType *AccessType `bun:"-" json:"access_type,omitempty"`
	Until      *time.Time  `json:"until,omitempty"`
	UserID     int64       `json:"user_id,omitempty"`
	World      *int        `json:"world,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error            string `json:"error"`
	SafeDisplayError string `json:"safe-display-error"`
}

// PlatformLink defines model for PlatformLink.
type PlatformLink struct {
	DisplayName *string `json:"display_name,omitempty"`

	// PlatformId ID of the platform the user id belongs to
	PlatformID     int    `bun:",pk" json:"platform_id"`
	PlatformUserID string `bun:",pk" json:"platform_user_id"`
	Primary        bool   `json:"primary"`
	UserID         int64  `json:"user_id"`
}

// Property defines model for Property.
type Property struct {
	Name    string  `json:"name"`
	Subject *string `json:"subject,omitempty"`
	Value   string  `json:"value"`
}

// Status defines model for Status.
type Status string

// TokenInfo defines model for TokenInfo.
type TokenInfo struct {
	AccountId   string    `json:"account_id"`
	DbCreated   time.Time `bun:",nullzero,notnull,default:current_timestamp,scanonly" json:"db_created,omitempty"`
	DbUpdated   time.Time `bun:",nullzero,notnull,default:current_timestamp" json:"db_updated,omitempty"`
	Id          string    `json:"id"`
	LastSuccess time.Time `json:"last_success,omitempty"`
	Name        string    `json:"name"`
	Permissions []string  `json:"permissions"`
}

// User defines model for User.
type User struct {
	Accounts              []Account              `bun:"rel:has-many,join:id=user_id" json:"accounts,omitempty"`
	Bans                  []Ban                  `bun:"rel:has-many,join:id=user_id" json:"bans,omitempty"`
	DbCreated             time.Time              `bun:",nullzero,notnull,default:current_timestamp,scanonly" json:"db_created,omitempty"`
	DbUpdated             time.Time              `bun:",nullzero,notnull,default:current_timestamp" json:"db_updated,omitempty"`
	EphemeralAssociations []EphemeralAssociation `bun:"rel:has-many,join:id=user_id" json:"ephemeral_associations,omitempty"`
	Id                    int64                  `bun:",pk,autoincrement" json:"id"`
	PlatformLinks         []PlatformLink         `bun:"rel:has-many,join:id=user_id" json:"platform_links,omitempty"`
}

// VerificationStatus defines model for VerificationStatus.
type VerificationStatus struct {
	Ban          *Ban          `json:"ban,omitempty"`
	PlatformLink *PlatformLink `json:"platform_link,omitempty"`
	Status       Status        `bun:"-" json:"status"`
}

// WorldLinks defines model for WorldLinks.
type WorldLinks = []int

// GuildIdent defines model for guild_ident.
type GuildIdent = string

// PlatformId defines model for platform_id.
type PlatformId = int

// PlatformUserId defines model for platform_user_id.
type PlatformUserId = string

// PropertyName defines model for property_name.
type PropertyName = string

// ServiceUuid defines model for service_uuid.
type ServiceUuid = string

// Subject defines model for subject.
type Subject = string

// TraitPlatformUserDisplayName defines model for trait_platform_user_display_name.
type TraitPlatformUserDisplayName = string

// TraitSecuredAuthentication defines model for trait_secured_authentication.
type TraitSecuredAuthentication = string

// TraitWorldView defines model for trait_world_view.
type TraitWorldView = int

// TraitWorldViewOptional defines model for trait_world_view_optional.
type TraitWorldViewOptional = int

// TraitErrorResp defines model for trait_error_resp.
type TraitErrorResp = Error

// PostChannelPlatformStatisticsParams defines parameters for PostChannelPlatformStatistics.
type PostChannelPlatformStatisticsParams struct {
	World TraitWorldView `form:"world" json:"world"`
}

// GetV1ConfigurationParams defines parameters for GetV1Configuration.
type GetV1ConfigurationParams struct {
	World *TraitWorldViewOptional `form:"world,omitempty" json:"world,omitempty"`
}

// GetPlatformUserUpdatesParams defines parameters for GetPlatformUserUpdates.
type GetPlatformUserUpdatesParams struct {
	World TraitWorldView `form:"world" json:"world"`
}

// GetPlatformUserParams defines parameters for GetPlatformUser.
type GetPlatformUserParams struct {
	// DisplayName Display name of the user of the platform user. Will be stored as the latest used display name by that user
	DisplayName *TraitPlatformUserDisplayName `form:"display_name,omitempty" json:"display_name,omitempty"`
}

// PutPlatformUserAPIKeyParams defines parameters for PutPlatformUserAPIKey.
type PutPlatformUserAPIKeyParams struct {
	// SkipRequirements Skip the variuse apikey requirements that might be in place
	SkipRequirements *bool                   `form:"skip-requirements,omitempty" json:"skip-requirements,omitempty"`
	World            *TraitWorldViewOptional `form:"world,omitempty" json:"world,omitempty"`
}

// GetPlatformUserAPIKeyNameParams defines parameters for GetPlatformUserAPIKeyName.
type GetPlatformUserAPIKeyNameParams struct {
	World *TraitWorldViewOptional `form:"world,omitempty" json:"world,omitempty"`
}

// GetVerificationPlatformUserUpdatesParams defines parameters for GetVerificationPlatformUserUpdates.
type GetVerificationPlatformUserUpdatesParams struct {
	World TraitWorldView `form:"world" json:"world"`
}

// GetVerificationPlatformUserStatusParams defines parameters for GetVerificationPlatformUserStatus.
type GetVerificationPlatformUserStatusParams struct {
	World TraitWorldView `form:"world" json:"world"`

	// DisplayName Display name of the user of the platform user. Will be stored as the latest used display name by that user
	DisplayName *TraitPlatformUserDisplayName `form:"display_name,omitempty" json:"display_name,omitempty"`
}

// PostVerificationPlatformUserRefreshParams defines parameters for PostVerificationPlatformUserRefresh.
type PostVerificationPlatformUserRefreshParams struct {
	World TraitWorldView `form:"world" json:"world"`
}

// PutVerificationPlatformUserTemporaryParams defines parameters for PutVerificationPlatformUserTemporary.
type PutVerificationPlatformUserTemporaryParams struct {
	World TraitWorldView `form:"world" json:"world"`
}

// PostChannelPlatformStatisticsJSONRequestBody defines body for PostChannelPlatformStatistics for application/json ContentType.
type PostChannelPlatformStatisticsJSONRequestBody = ChannelMetadata

// PutPlatformUserAPIKeyJSONRequestBody defines body for PutPlatformUserAPIKey for application/json ContentType.
type PutPlatformUserAPIKeyJSONRequestBody = APIKeyData

// PutPlatformUserBanJSONRequestBody defines body for PutPlatformUserBan for application/json ContentType.
type PutPlatformUserBanJSONRequestBody = Ban

// PutVerificationPlatformUserTemporaryJSONRequestBody defines body for PutVerificationPlatformUserTemporary for application/json ContentType.
type PutVerificationPlatformUserTemporaryJSONRequestBody = EphemeralAssociation

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /v1/channels/{platform_id}/{channel}/statistics)
	PostChannelPlatformStatistics(c *gin.Context, platformId PlatformId, channel string, params PostChannelPlatformStatisticsParams)

	// (GET /v1/configuration)
	GetV1Configuration(c *gin.Context, params GetV1ConfigurationParams)

	// (GET /v1/guilds/{guild_ident}/users)
	GetGuildUsers(c *gin.Context, guildIdent GuildIdent)

	// (GET /v1/platform/{platform_id}/users/updates)
	GetPlatformUserUpdates(c *gin.Context, platformId PlatformId, params GetPlatformUserUpdatesParams)

	// (GET /v1/platform/{platform_id}/users/{platform_user_id})
	GetPlatformUser(c *gin.Context, platformId PlatformId, platformUserId PlatformUserId, params GetPlatformUserParams)

	// (PUT /v1/platform/{platform_id}/users/{platform_user_id}/apikey)
	PutPlatformUserAPIKey(c *gin.Context, platformId PlatformId, platformUserId PlatformUserId, params PutPlatformUserAPIKeyParams)

	// (GET /v1/platform/{platform_id}/users/{platform_user_id}/apikey/name)
	GetPlatformUserAPIKeyName(c *gin.Context, platformId PlatformId, platformUserId PlatformUserId, params GetPlatformUserAPIKeyNameParams)

	// (PUT /v1/platform/{platform_id}/users/{platform_user_id}/ban)
	PutPlatformUserBan(c *gin.Context, platformId PlatformId, platformUserId PlatformUserId)

	// (POST /v1/platform/{platform_id}/users/{platform_user_id}/refresh)
	PostPlatformUserRefresh(c *gin.Context, platformId PlatformId, platformUserId PlatformUserId)

	// (GET /v1/services/{service_uuid}/properties)
	GetServiceProperties(c *gin.Context, serviceUuid ServiceUuid)

	// (GET /v1/services/{service_uuid}/properties/{subject})
	GetServiceSubjectProperties(c *gin.Context, serviceUuid ServiceUuid, subject Subject)

	// (PUT /v1/services/{service_uuid}/properties/{subject})
	PutServiceSubjectProperties(c *gin.Context, serviceUuid ServiceUuid, subject Subject)

	// (GET /v1/services/{service_uuid}/properties/{subject}/{property_name})
	GetServiceSubjectProperty(c *gin.Context, serviceUuid ServiceUuid, subject Subject, propertyName PropertyName)

	// (PUT /v1/services/{service_uuid}/properties/{subject}/{property_name})
	PutServiceSubjectProperty(c *gin.Context, serviceUuid ServiceUuid, subject Subject, propertyName PropertyName)

	// (GET /v1/verification/platform/{platform_id}/users/updates)
	GetVerificationPlatformUserUpdates(c *gin.Context, platformId PlatformId, params GetVerificationPlatformUserUpdatesParams)

	// (GET /v1/verification/platform/{platform_id}/users/{platform_user_id})
	GetVerificationPlatformUserStatus(c *gin.Context, platformId PlatformId, platformUserId PlatformUserId, params GetVerificationPlatformUserStatusParams)

	// (POST /v1/verification/platform/{platform_id}/users/{platform_user_id}/refresh)
	PostVerificationPlatformUserRefresh(c *gin.Context, platformId PlatformId, platformUserId PlatformUserId, params PostVerificationPlatformUserRefreshParams)

	// (PUT /v1/verification/platform/{platform_id}/users/{platform_user_id}/temporary)
	PutVerificationPlatformUserTemporary(c *gin.Context, platformId PlatformId, platformUserId PlatformUserId, params PutVerificationPlatformUserTemporaryParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostChannelPlatformStatistics operation middleware
func (siw *ServerInterfaceWrapper) PostChannelPlatformStatistics(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "channel" -------------
	var channel string

	err = runtime.BindStyledParameterWithOptions("simple", "channel", c.Param("channel"), &channel, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter channel: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostChannelPlatformStatisticsParams

	// ------------- Required query parameter "world" -------------

	if paramValue := c.Query("world"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument world is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "world", c.Request.URL.Query(), &params.World)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter world: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostChannelPlatformStatistics(c, platformId, channel, params)
}

// GetV1Configuration operation middleware
func (siw *ServerInterfaceWrapper) GetV1Configuration(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1ConfigurationParams

	// ------------- Optional query parameter "world" -------------

	err = runtime.BindQueryParameter("form", true, false, "world", c.Request.URL.Query(), &params.World)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter world: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Configuration(c, params)
}

// GetGuildUsers operation middleware
func (siw *ServerInterfaceWrapper) GetGuildUsers(c *gin.Context) {

	var err error

	// ------------- Path parameter "guild_ident" -------------
	var guildIdent GuildIdent

	err = runtime.BindStyledParameterWithOptions("simple", "guild_ident", c.Param("guild_ident"), &guildIdent, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter guild_ident: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGuildUsers(c, guildIdent)
}

// GetPlatformUserUpdates operation middleware
func (siw *ServerInterfaceWrapper) GetPlatformUserUpdates(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlatformUserUpdatesParams

	// ------------- Required query parameter "world" -------------

	if paramValue := c.Query("world"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument world is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "world", c.Request.URL.Query(), &params.World)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter world: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPlatformUserUpdates(c, platformId, params)
}

// GetPlatformUser operation middleware
func (siw *ServerInterfaceWrapper) GetPlatformUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "platform_user_id" -------------
	var platformUserId PlatformUserId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_user_id", c.Param("platform_user_id"), &platformUserId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlatformUserParams

	// ------------- Optional query parameter "display_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "display_name", c.Request.URL.Query(), &params.DisplayName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter display_name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPlatformUser(c, platformId, platformUserId, params)
}

// PutPlatformUserAPIKey operation middleware
func (siw *ServerInterfaceWrapper) PutPlatformUserAPIKey(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "platform_user_id" -------------
	var platformUserId PlatformUserId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_user_id", c.Param("platform_user_id"), &platformUserId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PutPlatformUserAPIKeyParams

	// ------------- Optional query parameter "skip-requirements" -------------

	err = runtime.BindQueryParameter("form", true, false, "skip-requirements", c.Request.URL.Query(), &params.SkipRequirements)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter skip-requirements: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "world" -------------

	err = runtime.BindQueryParameter("form", true, false, "world", c.Request.URL.Query(), &params.World)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter world: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutPlatformUserAPIKey(c, platformId, platformUserId, params)
}

// GetPlatformUserAPIKeyName operation middleware
func (siw *ServerInterfaceWrapper) GetPlatformUserAPIKeyName(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "platform_user_id" -------------
	var platformUserId PlatformUserId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_user_id", c.Param("platform_user_id"), &platformUserId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlatformUserAPIKeyNameParams

	// ------------- Optional query parameter "world" -------------

	err = runtime.BindQueryParameter("form", true, false, "world", c.Request.URL.Query(), &params.World)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter world: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPlatformUserAPIKeyName(c, platformId, platformUserId, params)
}

// PutPlatformUserBan operation middleware
func (siw *ServerInterfaceWrapper) PutPlatformUserBan(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "platform_user_id" -------------
	var platformUserId PlatformUserId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_user_id", c.Param("platform_user_id"), &platformUserId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutPlatformUserBan(c, platformId, platformUserId)
}

// PostPlatformUserRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostPlatformUserRefresh(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "platform_user_id" -------------
	var platformUserId PlatformUserId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_user_id", c.Param("platform_user_id"), &platformUserId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPlatformUserRefresh(c, platformId, platformUserId)
}

// GetServiceProperties operation middleware
func (siw *ServerInterfaceWrapper) GetServiceProperties(c *gin.Context) {

	var err error

	// ------------- Path parameter "service_uuid" -------------
	var serviceUuid ServiceUuid

	err = runtime.BindStyledParameterWithOptions("simple", "service_uuid", c.Param("service_uuid"), &serviceUuid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_uuid: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServiceProperties(c, serviceUuid)
}

// GetServiceSubjectProperties operation middleware
func (siw *ServerInterfaceWrapper) GetServiceSubjectProperties(c *gin.Context) {

	var err error

	// ------------- Path parameter "service_uuid" -------------
	var serviceUuid ServiceUuid

	err = runtime.BindStyledParameterWithOptions("simple", "service_uuid", c.Param("service_uuid"), &serviceUuid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_uuid: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "subject" -------------
	var subject Subject

	err = runtime.BindStyledParameterWithOptions("simple", "subject", c.Param("subject"), &subject, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter subject: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServiceSubjectProperties(c, serviceUuid, subject)
}

// PutServiceSubjectProperties operation middleware
func (siw *ServerInterfaceWrapper) PutServiceSubjectProperties(c *gin.Context) {

	var err error

	// ------------- Path parameter "service_uuid" -------------
	var serviceUuid ServiceUuid

	err = runtime.BindStyledParameterWithOptions("simple", "service_uuid", c.Param("service_uuid"), &serviceUuid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_uuid: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "subject" -------------
	var subject Subject

	err = runtime.BindStyledParameterWithOptions("simple", "subject", c.Param("subject"), &subject, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter subject: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutServiceSubjectProperties(c, serviceUuid, subject)
}

// GetServiceSubjectProperty operation middleware
func (siw *ServerInterfaceWrapper) GetServiceSubjectProperty(c *gin.Context) {

	var err error

	// ------------- Path parameter "service_uuid" -------------
	var serviceUuid ServiceUuid

	err = runtime.BindStyledParameterWithOptions("simple", "service_uuid", c.Param("service_uuid"), &serviceUuid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_uuid: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "subject" -------------
	var subject Subject

	err = runtime.BindStyledParameterWithOptions("simple", "subject", c.Param("subject"), &subject, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter subject: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "property_name" -------------
	var propertyName PropertyName

	err = runtime.BindStyledParameterWithOptions("simple", "property_name", c.Param("property_name"), &propertyName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter property_name: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServiceSubjectProperty(c, serviceUuid, subject, propertyName)
}

// PutServiceSubjectProperty operation middleware
func (siw *ServerInterfaceWrapper) PutServiceSubjectProperty(c *gin.Context) {

	var err error

	// ------------- Path parameter "service_uuid" -------------
	var serviceUuid ServiceUuid

	err = runtime.BindStyledParameterWithOptions("simple", "service_uuid", c.Param("service_uuid"), &serviceUuid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_uuid: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "subject" -------------
	var subject Subject

	err = runtime.BindStyledParameterWithOptions("simple", "subject", c.Param("subject"), &subject, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter subject: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "property_name" -------------
	var propertyName PropertyName

	err = runtime.BindStyledParameterWithOptions("simple", "property_name", c.Param("property_name"), &propertyName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter property_name: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutServiceSubjectProperty(c, serviceUuid, subject, propertyName)
}

// GetVerificationPlatformUserUpdates operation middleware
func (siw *ServerInterfaceWrapper) GetVerificationPlatformUserUpdates(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVerificationPlatformUserUpdatesParams

	// ------------- Required query parameter "world" -------------

	if paramValue := c.Query("world"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument world is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "world", c.Request.URL.Query(), &params.World)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter world: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVerificationPlatformUserUpdates(c, platformId, params)
}

// GetVerificationPlatformUserStatus operation middleware
func (siw *ServerInterfaceWrapper) GetVerificationPlatformUserStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "platform_user_id" -------------
	var platformUserId PlatformUserId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_user_id", c.Param("platform_user_id"), &platformUserId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVerificationPlatformUserStatusParams

	// ------------- Required query parameter "world" -------------

	if paramValue := c.Query("world"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument world is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "world", c.Request.URL.Query(), &params.World)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter world: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "display_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "display_name", c.Request.URL.Query(), &params.DisplayName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter display_name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVerificationPlatformUserStatus(c, platformId, platformUserId, params)
}

// PostVerificationPlatformUserRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostVerificationPlatformUserRefresh(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "platform_user_id" -------------
	var platformUserId PlatformUserId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_user_id", c.Param("platform_user_id"), &platformUserId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostVerificationPlatformUserRefreshParams

	// ------------- Required query parameter "world" -------------

	if paramValue := c.Query("world"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument world is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "world", c.Request.URL.Query(), &params.World)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter world: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostVerificationPlatformUserRefresh(c, platformId, platformUserId, params)
}

// PutVerificationPlatformUserTemporary operation middleware
func (siw *ServerInterfaceWrapper) PutVerificationPlatformUserTemporary(c *gin.Context) {

	var err error

	// ------------- Path parameter "platform_id" -------------
	var platformId PlatformId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_id", c.Param("platform_id"), &platformId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "platform_user_id" -------------
	var platformUserId PlatformUserId

	err = runtime.BindStyledParameterWithOptions("simple", "platform_user_id", c.Param("platform_user_id"), &platformUserId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform_user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PutVerificationPlatformUserTemporaryParams

	// ------------- Required query parameter "world" -------------

	if paramValue := c.Query("world"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument world is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "world", c.Request.URL.Query(), &params.World)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter world: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutVerificationPlatformUserTemporary(c, platformId, platformUserId, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/channels/:platform_id/:channel/statistics", wrapper.PostChannelPlatformStatistics)
	router.GET(options.BaseURL+"/v1/configuration", wrapper.GetV1Configuration)
	router.GET(options.BaseURL+"/v1/guilds/:guild_ident/users", wrapper.GetGuildUsers)
	router.GET(options.BaseURL+"/v1/platform/:platform_id/users/updates", wrapper.GetPlatformUserUpdates)
	router.GET(options.BaseURL+"/v1/platform/:platform_id/users/:platform_user_id", wrapper.GetPlatformUser)
	router.PUT(options.BaseURL+"/v1/platform/:platform_id/users/:platform_user_id/apikey", wrapper.PutPlatformUserAPIKey)
	router.GET(options.BaseURL+"/v1/platform/:platform_id/users/:platform_user_id/apikey/name", wrapper.GetPlatformUserAPIKeyName)
	router.PUT(options.BaseURL+"/v1/platform/:platform_id/users/:platform_user_id/ban", wrapper.PutPlatformUserBan)
	router.POST(options.BaseURL+"/v1/platform/:platform_id/users/:platform_user_id/refresh", wrapper.PostPlatformUserRefresh)
	router.GET(options.BaseURL+"/v1/services/:service_uuid/properties", wrapper.GetServiceProperties)
	router.GET(options.BaseURL+"/v1/services/:service_uuid/properties/:subject", wrapper.GetServiceSubjectProperties)
	router.PUT(options.BaseURL+"/v1/services/:service_uuid/properties/:subject", wrapper.PutServiceSubjectProperties)
	router.GET(options.BaseURL+"/v1/services/:service_uuid/properties/:subject/:property_name", wrapper.GetServiceSubjectProperty)
	router.PUT(options.BaseURL+"/v1/services/:service_uuid/properties/:subject/:property_name", wrapper.PutServiceSubjectProperty)
	router.GET(options.BaseURL+"/v1/verification/platform/:platform_id/users/updates", wrapper.GetVerificationPlatformUserUpdates)
	router.GET(options.BaseURL+"/v1/verification/platform/:platform_id/users/:platform_user_id", wrapper.GetVerificationPlatformUserStatus)
	router.POST(options.BaseURL+"/v1/verification/platform/:platform_id/users/:platform_user_id/refresh", wrapper.PostVerificationPlatformUserRefresh)
	router.PUT(options.BaseURL+"/v1/verification/platform/:platform_id/users/:platform_user_id/temporary", wrapper.PutVerificationPlatformUserTemporary)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc6Y/buBX/Vwi1wH6Rx9lsWhQD5IMTu6mxiTOdY6dFNhBo6dnmWiK1JOWJO/D/XvDQ",
	"TdtS5srs5ttYIvkO/vguPs2tF7IkZRSoFN7prZdijhOQwPWvZUbiKCARUKl+RiBCTlJJGPVOvaur6Rgx",
	"jihOALEF0oM93yPqZYrlyvM99c47ra3jexx+zwiHyDuVPAPfE+EKEqwIyG2qhgvJCV16u53vpTGWC8aT",
	"gERtDl6g1+ga5oJI8NGP6DW6BJyIFPDaRy/RazQmImR8D0/VlTvwRKiEJfA6U5kAbjk7RCEf1lN0zlLg",
	"chuY5dwkamP6rS+Ab0gIQZa5dJtR8nsGiERqa+UKkB3uVmZtrZ5sZPPfIJR7BMzf9ltTckxkUNd/REQa",
	"41KbdXHH5m0BZiWxmpb/na+lH56gaxLHaA5ISMYhQljoQTGWIKQaEqGouuB8i+QK6zc8V+DvGfBtKWiN",
	"vS7SCQgzDlGAM7kCKkmIjShWjSvAkSZm1x/Vh32NPm8Yj6NgQ+CmoNIQQo/oe5qaiwdMbwqOj1E5sOpO",
	"8SBSRgVoQ2ZoAOeMB+qFehYyKq1hw2kaW80MfxNGi+Xqf+Ww8E69vwxLUzk0b8VwopY0BOuAmtAoZYRK",
	"dIMFyiiex4AkQ2qJGCSgLcs4UnoCIb3Wpr568VMbo6MwBCGQZGugiNANjknkNRTIOAEq9Qov2itMzSSk",
	"x6qznXK2IRFE5iQamdS00dn0Z9iOsdQKsFaGGF3ilKxh2178cgUIp0RJKUCiBePFKfL8JqiUeSMJ5o51",
	"LkAiUjmBYsWyOFKnTR9EM61yOLFEKeaShFmMeXFQT9DlCjigEFPEaLxV8xkFlEI5Rv/AYcgyKk/QBUhJ",
	"6BJhROGmTudGHXe2Ac5JZNhgcaSWKwWbMxYDpp6BXg7/T7m2Snk/F1OYMW0736p7Zi1TXd1ue2WVvQZr",
	"YQptrZQtYsVDwvNhZFGbQAQCumA8hKi9Ow0ZNAtOvjUiL/XjWw9olqjh//r4YRJcfzx/P/Z87/109vNk",
	"bH9+blLyvS8DhlMyCFkES6AD+CI5Hki81LLPMyXrQDM0MvvkwKNmQhsLCYlwWLCCKuYcb9VvvASX3fDV",
	"dgVr2NaXO2QALtVpnNIFa5FRsi3ZQD0biDVJB7ldG2jDADy3jh1UwCE+XWExSDDd+r8xQk9J9NoiV0UW",
	"SkEhSxJMldEvJStQ6XshByxBe3qFfSyV08ESBpIk4DqgESbxNsCpW1HRPOi34n2qw6dZHP8POPMpk+pv",
	"P4IFzmJ5GmacA5WBYkFInKS+CDFVBkDrKJoHWRp9+1xrZuFLak5gazt7HJsFx6HEcRDDBmL3VproPDYB",
	"Q69jpGf2PHokag+zWrb+fTruJqCfrrWIMRYySFhEFqQPvhNG5eoAwnPD25pYifoLSoTKv78qqeTL1AW7",
	"EsCnY7WECWGcZI0fFxLL7KjxuTCj1KzNTZBnWcf0e725fqeGdtVzbe2dJcYxXTsEaFE6V+M6k9Gr5iQk",
	"4KQuzl4qKvHrI06+9K7p6nT6YmNw5ST8ItrMrV3V0JZYqCilznzFpbg86BtM2x6NA7ZBaBt7VJK4O8bv",
	"DNWGekpxDSN+zqtLtrcrTCnEH0DiyBlJHjxh3V2wpaNYLmi1DI8rpMkJHWC+tmhLgAjwAqjTRO+xdMru",
	"ZHLfjL0KEZIDTtQPx7wDEDa0/JLR6lJOsRldkGXGi2SyLrB2Sfqd9lVuCyYhSRnHfBuY0CzoNMvYvZjQ",
	"tYnqoogYT3tW4+AQEK7VEu/1Cq187D0RUuULmoxAhk5LAQ1VNhnvIFtdEJeKJ+kKEuA4HgnBQrJH03Z5",
	"aWPrQ2JXovDHtxAdA6RDPm/nUpLOq9v4yx+3TwhewMAWUQb7hjW3Vw9zznVt3JlNGxXCHLagUV9qJ7yH",
	"SpnTcavSVKR0RCW/MaNLldkd25acyb5BlKumeSiIyOlUYNCdVjX11xFwHkW3TeJ9ezBHUbZeCc6ZK0k7",
	"sWALrz2cWqXQ2Xq3wXEGxwFrrboZ7WLroggb82R89Pbt5OIiGE9m08k4uJr9PPt4PfP8/Pm789HscjIO",
	"ajl7410thT8wM7icfDj7eD46/+/hNVzjLH+jt28/Xs0ug9nHSzulNWTyn7PpueP5dPbL6P20xaZ9+2Y0",
	"mzkmnU/+fTU9n3yYWJofJpd3KlKU1QCXQc+zdRcCvufTD55P79G8Th9FVlSR7k+KQxFdCjwhQhBG++TP",
	"XQkfympKHNa5cNkTZUT3Qrl7hJ7X7h69RJabcKWQOabdOX5jvM/TcfvdHjx8fS0PxANcRuLdIeKM458U",
	"M93DpC6hmo8zyQgNOSRAZT1ILNK0TpqqBc5PqKG2VXTZvF+Ak4W9DSzjqboFnJuyTQcLUlNZX0X1qwI2",
	"xLOTXSJWEmWH76mm8s0air6gJHJ7oWhbXQDmwEeZXBXXpjqG149L+K2kTM0eEBsfSSJj9UYXI9E15gK9",
	"RFXto9HZVIW7wIXJkjYvFVMsBYpT4p16P528OHmh3BiWK83LcPPjMDSVGzG8rQT2u+Gtfb4bKsUQIUnY",
	"6nj55OxBsBP73Zm7t6wkNqxmHR2Gt67gd599L2XC0ZjzlsUxhBKVcqI5FhAhRu0Vqrn0ReXyCNMICbzR",
	"d4aJvrtdESEZJyGOUZrxlAkQnta9qXZMI5UEMiFtoSyH7kWpXKMvEPINi7b3duPerCo2jrWNu2q3/y9d",
	"d+EKSfaS/GE7AQyhn/bNLzgdtlsAdr73N8Nil5mV9oad5kOfhmZBbwkOyLwDiTCqjVW/JCaU0CXiEMMG",
	"U4nU0VXeRb1XIOEZpebO3HYAoTmTLZi8A/nLj/XKonuH7gcgNUJ7N6SzWh2NFXfYUe1G6yan58kv+2N2",
	"n+0mm3u44W2lz243LIro7h3naj+xqTAVVU3bGcIh1to7QaOiDBtvfW09ftU10MBeTv7qobwHzXRJzAFx",
	"SNgGIrTgrKxi/SBQxYU6EKK9wJXm+QHBoRMaByZiWx7eaPcDkeZZIGIspmltfErY3MEQ9MVbtVmzQFju",
	"rRpOVWtpaEL+/Vh7z+gSpSyOjS0REkHeHaWNCIRANuqdBmO+mgMj1aLjVTHs0cHyxEh49eIfR3Ss8hyW",
	"SR9RhmCj1kR4g0msu9CijJt90L4ZpcAJi+6CMN8zUfin/DqtN+TuHgt1gelts/a7O+IPa02fPwgUgcQk",
	"PorMPyEkH8049URKq9rfGV0Hmoe/Fm3DsnPyGxXaHWT4XppJd59m+4yMzqbINDw2UoWsdkZMx6PX2v4G",
	"iTVJtQPeYE4yUbQ82nA/0ZZNd4AmZLmSKvggVLFU9qk3eod1haE63dVHXN6sf36YHKbSXnsP6cuzOvB3",
	"OjrDvJzew2g3umS3CHPIARQhydS4ZnOsilE4CXWaU2+UPWj4K228D+gCKlS+O4KnsolfCWNbN3xkUfdZ",
	"8DeY2gzwB4GWNy/zXniTuc1BhYl5QnTMoL/B9IEKPrqQ+r3Ic5/WlMOCg1g9ERSdRct/KgsrEEaWt7wd",
	"RsUTEZZYVyg5yIxT87EVhRuTL5q3Cwm8PmGFBZoD0HxFiE7QjEnlBYjQ34VIvAaE0QJukICQ0chd4azC",
	"/Nxq7slC/KeCmK3vieFt9Vu/3bB+L7LfL8dxUSI8XAe6MKPOqoPupOtuV1R5P0/70uOQi/1DGpW+rrj2",
	"8WfhGo8DZnhrW6KO5eF22NESooXOhRn+zSPo6+s/rxxfY2tTyEAgyiRa2aucvMoDUVGmfUJoHHcYeY/c",
	"kaSzEyDOsucGiD98nNLHJgxvax+397YR284WYvvdPjw7+9Ah9qz9a4S+BmXb2Zx0QI+EL1LFwqSBm2bT",
	"wJ/VLGwqPR+PdNNUJXnoxqnajvLIt0+OPqTvd1HP6C6qO6p7X0yZy+kahm23Vw8IX+Qz/twI/iNXLO/3",
	"uusugH7CktO99tZ9VZnKcVAftGC178TfU/GqU7jrOvu98qDneKt1pxNSNGE9ozOSffOdZWfZ3uNwWSj8",
	"YS4u3B8IdL7J6MyD679f1bfEqDQ3OkuyAYpwoq962KIwJc/17FXa0vVhqTakf/qscKrSzPwoZTy23eji",
	"dDjEKTlZYC5WZAM8BbwWJyFLlM/7fwAAAP//DMpS0BpRAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
