// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package api

import (
	"github.com/gorilla/mux"
	"net/http"
)

// ConfigurationInterface is interface for /configuration root endpoint
type ConfigurationInterface interface { // Get is the handler for GET /configuration
	// Get a configuration containing relevant information for running a service bot
	Get(http.ResponseWriter, *http.Request)
}

// ConfigurationInterfaceRoutes is routing for /configuration root endpoint
func ConfigurationInterfaceRoutes(r *mux.Router, i ConfigurationInterface) {
	r.HandleFunc("/v1/configuration", i.Get).Methods("GET")
}
