// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package api

import (
	"github.com/gorilla/mux"

	"github.com/vennekilde/gw2verify/internal/api/handlers/configuration"
	"github.com/vennekilde/gw2verify/internal/api/handlers/updates"
	"github.com/vennekilde/gw2verify/internal/api/handlers/users"
)

func initRoutes(r *mux.Router) {

	ConfigurationInterfaceRoutes(r, configuration.ConfigurationAPI{})
	UpdatesInterfaceRoutes(r, updates.UpdatesAPI{})
	UsersInterfaceRoutes(r, users.UsersAPI{})
}
