// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package api

import (
	"github.com/gorilla/mux"

	"github.com/vennekilde/gw2verify/internal/api/handlers/v1"
)

func initRoutes(r *mux.Router) {

	V1InterfaceRoutes(r, v1.V1API{})
}
