// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package api

import (
	"github.com/gorilla/mux"
	"net/http"
)

// UpdatesInterface is interface for /updates root endpoint
type UpdatesInterface interface { // Service_idsubscribeGet is the handler for GET /updates/{service_id}/subscribe
	// Long polling rest endpoint for receiving verification updates
	Service_idsubscribeGet(http.ResponseWriter, *http.Request)
}

// UpdatesInterfaceRoutes is routing for /updates root endpoint
func UpdatesInterfaceRoutes(r *mux.Router, i UpdatesInterface) {
	r.HandleFunc("/v1/updates/{service_id}/subscribe", i.Service_idsubscribeGet).Methods("GET")
}
