// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

type AccessType string

const (
	AccessTypeHOME_WORLD   AccessType = "HOME_WORLD"
	AccessTypeLINKED_WORLD AccessType = "LINKED_WORLD"
)
