// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type APIKeyName struct {
	Name string `json:"name" validate:"nonzero"`
}

func (s APIKeyName) Validate() error {

	return validator.Validate(s)
}
