// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type APIKeyData struct {
	Apikey  string `json:"apikey" validate:"nonzero"`
	Primary bool   `json:"primary"`
}

func (s APIKeyData) Validate() error {

	return validator.Validate(s)
}
