// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type BanData struct {
	Duration int64  `json:"duration" validate:"nonzero"`
	Reason   string `json:"reason" validate:"nonzero"`
}

func (s BanData) Validate() error {

	return validator.Validate(s)
}
