// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Configuration struct {
	Expiration_time                  int   `json:"expiration_time" validate:"nonzero"`
	Home_world                       int   `json:"home_world" validate:"nonzero"`
	Link_worlds                      []int `json:"link_worlds" validate:"nonzero"`
	Temporary_access_expiration_time int   `json:"temporary_access_expiration_time" validate:"nonzero"`
}

func (s Configuration) Validate() error {

	return validator.Validate(s)
}
