// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

type EnumVerificationUpdateType string

const (
	EnumVerificationUpdateTypeVERIFICATION  EnumVerificationUpdateType = "VERIFICATION"
	EnumVerificationUpdateTypeCONFIGURATION EnumVerificationUpdateType = "CONFIGURATION"
)
