// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

type EnumVerificationStatusStatus string

const (
	EnumVerificationStatusStatusACCESS_DENIED_UNKNOWN                 EnumVerificationStatusStatus = "ACCESS_DENIED_UNKNOWN"
	EnumVerificationStatusStatusACCESS_GRANTED_HOME_WORLD             EnumVerificationStatusStatus = "ACCESS_GRANTED_HOME_WORLD"
	EnumVerificationStatusStatusACCESS_GRANTED_LINKED_WORLD           EnumVerificationStatusStatus = "ACCESS_GRANTED_LINKED_WORLD"
	EnumVerificationStatusStatusACCESS_GRANTED_HOME_WORLD_TEMPORARY   EnumVerificationStatusStatus = "ACCESS_GRANTED_HOME_WORLD_TEMPORARY"
	EnumVerificationStatusStatusACCESS_GRANTED_LINKED_WORLD_TEMPORARY EnumVerificationStatusStatus = "ACCESS_GRANTED_LINKED_WORLD_TEMPORARY"
	EnumVerificationStatusStatusACCESS_DENIED_ACCOUNT_NOT_LINKED      EnumVerificationStatusStatus = "ACCESS_DENIED_ACCOUNT_NOT_LINKED"
	EnumVerificationStatusStatusACCESS_DENIED_EXPIRED                 EnumVerificationStatusStatus = "ACCESS_DENIED_EXPIRED"
	EnumVerificationStatusStatusACCESS_DENIED_INVALID_WORLD           EnumVerificationStatusStatus = "ACCESS_DENIED_INVALID_WORLD"
	EnumVerificationStatusStatusACCESS_DENIED_BANNED                  EnumVerificationStatusStatus = "ACCESS_DENIED_BANNED"
	EnumVerificationStatusStatusACCESS_DENIED_REQUIREMENT_NOT_MET     EnumVerificationStatusStatus = "ACCESS_DENIED_REQUIREMENT_NOT_MET"
)
