// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Error struct {
	Error            string `json:"error" validate:"nonzero"`
	SafeDisplayError string `json:"safe-display-error" validate:"nonzero"`
}

func (s Error) Validate() error {

	return validator.Validate(s)
}
