// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type TemporaryData struct {
	Access_type  AccessType `json:"access_type,omitempty"`
	Display_name string     `json:"display_name,omitempty"`
	World        int        `json:"world,omitempty"`
}

func (s TemporaryData) Validate() error {

	return validator.Validate(s)
}
