CREATE TABLE "public"."worlds" (
    "id" integer,
    "name" character varying(30),
    "population" character varying(30),
    CONSTRAINT "worlds_id" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "worlds" ("id", "name", "population") VALUES
    (1001,	'Anvil Rock',	'Full'),
    (1002,	'Borlis Pass',	'High'),
    (1003,	'Yak''s Bend',	'VeryHigh'),
    (1004,	'Henge of Denravi',	'VeryHigh'),
    (1005,	'Maguuma',	'Full'),
    (1006,	'Sorrow''s Furnace',	'High'),
    (1007,	'Gate of Madness',	'High'),
    (1008,	'Jade Quarry',	'Full'),
    (1009,	'Fort Aspenwood',	'Full'),
    (1010,	'Ehmry Bay',	'High'),
    (1011,	'Stormbluff Isle',	'Full'),
    (1012,	'Darkhaven',	'High'),
    (1013,	'Sanctum of Rall',	'High'),
    (1014,	'Crystal Desert',	'VeryHigh'),
    (1015,	'Isle of Janthir',	'Medium'),
    (1016,	'Sea of Sorrows',	'Full'),
    (1017,	'Tarnished Coast',	'VeryHigh'),
    (1018,	'Northern Shiverpeaks',	'High'),
    (1019,	'Blackgate',	'Full'),
    (1020,	'Ferguson''s Crossing',	'VeryHigh'),
    (1021,	'Dragonbrand',	'VeryHigh'),
    (1022,	'Kaineng',	'Medium'),
    (1023,	'Devona''s Rest',	'Medium'),
    (1024,	'Eredon Terrace',	'Full'),
    (2001,	'Fissure of Woe',	'Medium'),
    (2002,	'Desolation',	'Full'),
    (2003,	'Gandara',	'Full'),
    (2004,	'Blacktide',	'Medium'),
    (2005,	'Ring of Fire',	'VeryHigh'),
    (2006,	'Underworld',	'VeryHigh'),
    (2007,	'Far Shiverpeaks',	'VeryHigh'),
    (2008,	'Whiteside Ridge',	'Medium'),
    (2009,	'Ruins of Surmia',	'High'),
    (2010,	'Seafarer''s Rest',	'Full'),
    (2011,	'Vabbi',	'Medium'),
    (2012,	'Piken Square',	'VeryHigh'),
    (2013,	'Aurora Glade',	'High'),
    (2014,	'Gunnar''s Hold',	'VeryHigh'),
    (2101,	'Jade Sea [FR]',	'High'),
    (2102,	'Fort Ranik [FR]',	'Medium'),
    (2103,	'Augury Rock [FR]',	'High'),
    (2104,	'Vizunah Square [FR]',	'Medium'),
    (2105,	'Arborstone [FR]',	'High'),
    (2201,	'Kodash [DE]',	'Medium'),
    (2202,	'Riverside [DE]',	'Full'),
    (2203,	'Elona Reach [DE]',	'VeryHigh'),
    (2204,	'Abaddon''s Mouth [DE]',	'High'),
    (2205,	'Drakkar Lake [DE]',	'High'),
    (2206,	'Miller''s Sound [DE]',	'Medium'),
    (2207,	'Dzagonur [DE]',	'Full'),
    (2301,	'Baruch Bay [SP]',	'VeryHigh');